apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
  name: spring-petclinic-tap
  namespace: tanzu-apps
  params:
    - name: run-image
      value: ghcr.io/dbha/spring-petclinic-tap
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/jaimegag/spring-petclinic-tap